export const ADD_ING = "ADD_ING"
export const REMOVE_ING = "REMOVE_ING"
export const INIT_ING = "INIT_ING"
export const FETCH_ING_ERROR = "FETCH_ING_ERROR"

export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAILED = "ORDER_FAILED"
export const ORDER_STARTED = "ORDER_STARTED"
export const INITIALIZE_PURCHASING = "INITIALIZE_PURCHASING"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const AUTH_REDIRECT = "AUTH_REDIRECT"